### ISSUE TITLE
google auth setup

### ISSUE THREAD

**Issue by gedw99** [joerdav/shopping-list#1]
Nice project. Its amazing how far you can get with just golang.

Could you let me and others know how you  setup the google auth ?

Wish we had a standard email based auth too. Any reason why you chose Google auth ?

**Comment by joerdav** [comment]
1. Create a new google cloud project
2. Configure the consent screen https://console.cloud.google.com/apis/credentials/consent
3. Create OAuth creds https://console.cloud.google.com/apis/credentials
4. Make sure to allow the redirect urls needed, for me it was: "http://localhost:7331/auth/redirect" and "https://shoplist.fly.dev/auth/redirect"

Then grab the ID&Secret for use with your app.

**Comment by joerdav** [comment]
Interesting! I need to take a look at this. I hope my answer helped though
